print('Welcome to the tip calculator.')
total_bill = int(input('What was the total bill? $'))
number_of_people = int(input('How many people to split the bill? '))
percentage_tip = int(input('What percentage tip would you like to give? 10, 12, or 15? '))
print(f'Each person should pay: ${total_bill*(1 + (percentage_tip/100))/number_of_people}')